# Generated by Django 4.1.7 on 2023-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='responseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_yyymm', models.CharField(max_length=100)),
                ('svillage', models.IntegerField(default=0)),
                ('household_no', models.IntegerField(default=0)),
                ('people_total', models.IntegerField(default=0)),
                ('birth_total', models.IntegerField(default=0)),
                ('death_m', models.IntegerField(default=0)),
                ('death_f', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('svillage',),
            },
        ),
    ]
