# Generated by Django 4.2.2 on 2023-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='howmanypeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='peopledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mprice', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='NKUSTnews',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='maker',
        ),
        migrations.DeleteModel(
            name='responseData',
        ),
        migrations.DeleteModel(
            name='StockInfo',
        ),
        migrations.DeleteModel(
            name='PhoneMaker',
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
