# Generated by Django 4.2.2 on 2023-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_howmanypeople_peopledata_delete_nkustnews_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='howmanypeople',
        ),
        migrations.RenameField(
            model_name='peopledata',
            old_name='name',
            new_name='statistic_yyymm',
        ),
        migrations.RemoveField(
            model_name='peopledata',
            name='code',
        ),
        migrations.RemoveField(
            model_name='peopledata',
            name='mprice',
        ),
        migrations.RemoveField(
            model_name='peopledata',
            name='price',
        ),
        migrations.AddField(
            model_name='peopledata',
            name='birth_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledata',
            name='death_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledata',
            name='death_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledata',
            name='household_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledata',
            name='people_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peopledata',
            name='svillage',
            field=models.IntegerField(default=0),
        ),
    ]
