# Generated by Django 4.2.2 on 2023-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_cpdata_delete_citypeopledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdata',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
